const ACTION_TYPES = {
  REST_LOADING: "REST_LOADING",
  REST_ERROR: "REST_ERROR",
  REST_SUCCESS: "REST_SUCCESS",

  BASKET_LOADING: "REST_LOADING",
  BASKET_ERROR: "REST_ERROR",
  BASKET_SUCCESS: "REST_SUCCESS",
  CREATE_ITEM: "CREATE_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
};
export default ACTION_TYPES;
